package deposit.networking.jsonProtocol;

public enum RequestType {
    LOGIN, LOGOUT, GET_USER_BY_USERNAME, GET_ALL_PACKAGES,
    SAVE_PACKAGE, UPDATE_PACKAGE, DELETE_PACKAGE,
    GET_ALL_PACKAGES_BY_NAME, GET_ALL_PACKAGES_BY_FROM, GET_ALL_PACKAGES_BY_TO
}
